.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH engrampa 1 "2014\-01\-17" "MATE"
.SH NAME
engrampa \- archive manager for MATE
.SH SYNOPSIS
.B engrampa
.RI [ OPTIONS... ]
.RI [ FILE... ]
.SH DESCRIPTION
Engrampa is a graphical interface to archiving utilities such as
tar and zip. It is a fork of File Roller. 
.P 
It supports most common operations such as creating, modifing and
extracting files from an archive. You can also view the contents of an
archive and open files contained in the archive.
.SH OPTIONS
.TP
.B \-a, \-\-add\-to=ARCHIVE 
Add files to the specified archive and quit the program
.TP
.B \-d, \-\-add FILE
Add files asking the name of the archive and quit the program
.TP
.B \-e, \-\-extract\-to=FOLDER
Extract archives to the specified folder and quit the program
.TP
.B \-f, \-\-extract 
Extract archives asking the destination folder and quit the program
.TP
.B \-h, \-\-extract\-here 
Extract archives using the archive name as destination folder and quit the program
.TP
.B \-\-default\-dir=FOLDER
Default folder to use for the '\-\-add' and '\-\-extract' commands
.TP
.B \-\-force
Create destination folder without asking confirmation
.P
This program also accepts the standard GTK options.
.SH AUTHORS
.B engrampa
is written by Paolo Bacchilega <paolo.bacch@tin.it> and Perberos
<perberos@gmail.com>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others) for File Roller and
adapted for Engrampa by Stefano Karapetsas <stefano@karapetsas.com>.
.SH SEE ALSO
.BR "gtk-options" (7),
.P
The online documentation available through the program's
.I Help
menu.
